trigger:
- release

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  imageName: 'pipeline-dotnet-docker'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/*.csproj'
    feedsToUse: config
    nugetConfigPath: NuGet.config    # Relative to root of the repository
    externalFeedCredentials: <Name of the NuGet service connection>

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)' # Update this to match your need

steps:
# ...
# do this after other tasks such as building
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
        
steps:

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

# this code takes all the files in $(Build.ArtifactStagingDirectory) and uploads them as an artifact of your build.
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'myWebsiteName'

# this code build and push an image to ACR.
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: Build
    displayName: Build job
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag) 

# Define Variables for Environments
variables:
- name: STAGE_ENVIRONMENT
  value: stage
- name: PROD_ENVIRONMENT
  value: prod  

## ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
 
#trigger:
#- master
 
#pool:
  #vmImage: 'windows-latest'
 
#variables:
  #solution: '**/*.sln'
  #buildPlatform: 'Any CPU'
  #buildConfiguration: 'Release'
 
#steps:
#- task: NuGetToolInstaller@1
 
#- task: NuGetCommand@2
  #inputs:
    #restoreSolution: '$(solution)'

# Use SonarCloud and SonarQube tools for measuring code quality and  Static Code Analysis
## Service Connection will be used to connect SonarCloud with Azure Repos/ Azure Pipelines
# - task: SonarCloudPrepare@1
#  inputs:
#    SonarCloud: 'sonar-connection'
#    organization: 'app-org'
#    scannerMode: 'MSBuild'
#    projectKey: 'app-project'
#    projectName: 'app-project'

#- task: VSBuild@1
  #inputs:
    #solution: '$(solution)'
    #msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    #platform: '$(buildPlatform)'
    #configuration: '$(buildConfiguration)'

#- task: DotNetCoreCLI@2
#  inputs:
#    command: test
#    projects: '**/*Test/*.csproj'
#    arguments: '/p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./MyCoverage/'
#    publishTestResults: true    

#- task: WhiteSource Bolt@20

# For .Net based applications, we can use the .Net Core CLI task to generate code coverage reports.
## coverlet.msbuild is a cross platform code coverage library for .NET. 
#- task: PublishCodeCoverageResults@1
#  displayName: 'Publish Code Coverage Results'
#  inputs:
#    codeCoverageTool: 'Cobertura'
#    summaryFileLocation: '$(Build.SourcesDirectory)/**/MyCoverage/coverage.cobertura.xml'
#    failIfCoverageEmpty: true
 
#- task: SonarCloudAnalyze@1
#- task: SonarCloudPublish@1
#  inputs:
#    pollingTimeoutSec: '300'


# Stage-1: Terraform Validate Stage
## Step-1: Publish Artifacts to Pipeline (Pipeline artifacts provide a way to share files between stages in a pipeline or between different pipelines. )
## Step-2: Install Latest Terraform (0.13.5) (Ideally not needed if we use default Ubuntu Agents)
## Step-3: Validate Terraform Manifests (terraform init, terraform validate)

stages:
- stage: TerraformValidate
  jobs:
    - job: TerraformValidateJob
      continueOnError: false
      steps:
      - task: PublishPipelineArtifact@1
        displayName: Publish Artifacts
        inputs:
          targetPath: '$(System.DefaultWorkingDirectory)/terraform-manifests'
          artifact: 'terraform-manifests-out'
          publishLocation: 'pipeline'
      - task: TerraformInstaller@0
        displayName: Terraform Install
        inputs:
          terraformVersion: 'latest'
      - task: TerraformCLI@0
        displayName: Terraform Init
        inputs:
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-manifests'
          backendType: 'azurerm'
          backendServiceArm: 'terraform-aks-azurerm-svc-con'
          backendAzureRmResourceGroupName: 'terraform-storage-rg'
          backendAzureRmStorageAccountName: 'terraformstatexlrwdrzs'
          backendAzureRmContainerName: 'tfstatefiles'
          backendAzureRmKey: 'aks-base.tfstate'
          allowTelemetryCollection: true
      - task: TerraformCLI@0
        displayName: Terraform Validate
        inputs:
          command: 'validate'
          workingDirectory: '$(System.DefaultWorkingDirectory)/terraform-manifests'
          allowTelemetryCollection: true

# Stage-2: Deploy Stages for Stage Environment
# Deployment-1: Deploy STAGE AKS Cluster
## Step-1: Define Variables for environments
## Step-2: Download RDP Secure File
## Step-3: Terraform Initialize (State Storage to store in Azure Storage Account for Stage AKS Cluster)
## Step-4: Terraform Plan (Create Plan)
## Step-5: Terraform Apply (Use the plan created in previous step)

- stage: DeployAKSClusters
  jobs:
    - deployment: DeploySTAGEAKSCluster
      displayName: DeploySTAGEAKSCluster
      pool:
        vmImage: 'windows-latest'
      environment: $(STAGE_ENVIRONMENT)      
      strategy:
        runOnce:
          deploy:
            steps:            
            - task: DownloadSecureFile@1
              displayName: Download RDP Key
              name: rdpkey
              inputs:
                secureFile: 'filekey for windows agent pool'
            - task: TerraformCLI@0
              displayName: Terraform Init
              inputs:
                command: 'init'
                workingDirectory: '$(Pipeline.Workspace)/terraform-manifests-out'
                backendType: 'azurerm'
                backendServiceArm: 'terraform-aks-azurerm-svc-con'
                backendAzureRmResourceGroupName: 'terraform-storage-rg'
                backendAzureRmStorageAccountName: 'terraformstatexlrwdrzs'
                backendAzureRmContainerName: 'tfstatefiles'
                backendAzureRmKey: 'aks-$(STAGE_ENVIRONMENT).tfstate'
                allowTelemetryCollection: true
            - task: TerraformCLI@0
              displayName: Terraform Plan
              inputs:
                command: 'plan'
                workingDirectory: '$(Pipeline.Workspace)/terraform-manifests-out'
                environmentServiceName: 'terraform-aks-azurerm-svc-con'
                commandOptions: '-var rdp_key=$(rdpkey.secureFilePath) -var environment=$(STAGE_ENVIRONMENT) -out $(Pipeline.Workspace)/terraform-manifests-out/$(STAGE_ENVIRONMENT)-$(Build.BuildId).out'
                allowTelemetryCollection: true
            - task: TerraformCLI@0
              displayName: Terraform Apply
              inputs:
                command: 'apply'
                workingDirectory: '$(Pipeline.Workspace)/terraform-manifests-out'
                environmentServiceName: 'terraform-aks-azurerm-svc-con'
                commandOptions: '$(Pipeline.Workspace)/terraform-manifests-out/$(STAGE_ENVIRONMENT)-$(Build.BuildId).out'
                allowTelemetryCollection: true

========================================================================================================================================================================================================================


# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service

trigger:
- release

resources:
- repo: self

variables:

 # Container registry service connection established during pipeline creation
 dockerRegistryServiceConnection: '8e06f498-fd9e-481c-8453-12d8c2da0245'
 imageRepository: 'app1nginxaks'
 containerRegistry: 'aksdevopsacr.azurecr.io'
 dockerfilePath: '**/Dockerfile'
 tag: '$(Build.BuildId)'
 imagePullSecret: 'aksdevopsacr1755e8d5-auth'

 # Agent VM image name
 vmImageName: 'windows-latest'
 

stages:
- stage: Build
 displayName: Build stage
 jobs:  
 - job: Build
   displayName: Build
   pool:
     vmImage: $(vmImageName)
   steps:
   - task: Docker@2
     displayName: Build and push an image to container registry
     inputs:
       command: buildAndPush
       repository: $(imageRepository)
       dockerfile: $(dockerfilePath)
       containerRegistry: $(dockerRegistryServiceConnection)
       tags: |
         $(tag)
         
   - upload: manifests
     artifact: manifests

- stage: Deploy
 displayName: Deploy stage
 dependsOn: Build

 jobs:
 - deployment: Deploy
   displayName: Deploy
   pool:
     vmImage: $(vmImageName)
   environment: 'staging'
   strategy:
     runOnce:
       deploy:
         steps:
         - task: KubernetesManifest@0
           displayName: Create imagePullSecret
           inputs:
             action: createSecret
             secretName: $(imagePullSecret)
             dockerRegistryEndpoint: $(dockerRegistryServiceConnection)
             
         - task: KubernetesManifest@0
           displayName: Deploy to Kubernetes cluster
           inputs:
             action: deploy
             manifests: |
               $(Pipeline.Workspace)/manifests/windows-app-deployment.yml
               $(Pipeline.Workspace)/manifests/windows-app-loadbalancer-service.yml
             imagePullSecrets: |
               $(imagePullSecret)
             containers: |
               $(containerRegistry)/$(imageRepository):$(tag)

